### ISSUE TITLE
Sync with GFDL

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA-internal/MOM6#19]
[See](https://github.com/JCSDA-internal/soca/issues/480)

@liuxiao37k and @jkbk2004 , could you have a look at this [branch](https://github.com/JCSDA-internal/MOM6/tree/feature/main-ecbuild) and make the necessary changes so we can build with BGC. I'm trying to synchronize with GFDL's `main` branch. All is OK except for BGC. Here's the link to the corresponding [soca branch](https://github.com/JCSDA-internal/soca/tree/feature/sync-with-gfdl), it builds without BGC but I have not yet adjusted the tests.

**Comment by liuxiao37k** [comment]
@guillaumevernieres  Can you please confirm the soca branch that you mentioned? thanks!
`Here's the link to the corresponding soca ...`

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Can you please confirm the soca branch that you mentioned? thanks!
> `Here's the link to the corresponding soca ...`

Oops ... Just updated the link in the "description".

**Comment by liuxiao37k** [comment]
@guillaumevernieres Potential solutions are provided in [this commit](https://github.com/JCSDA-internal/MOM6/commit/0a62d4fc47efc8f72580465b6b02825d37fc5407).
